In [56]:
import numpy as np

import solutions.week01 as sln
import importlib

importlib.reload(sln)

row_matrix = np.array([
    [13, 1, 7],
    [ 4, 3, 6],
    [-1, 2, 8],
])

col_matrix = np.array([
    [ 3, 4,  3],
    [ 1, 3,  2],
    [ 9, 8, -1],
])

sln.iterated_removal_of_dominated_strategies(row_matrix,col_matrix)

(array([[13,  1,  7],
        [ 4,  3,  6],
        [-1,  2,  8]]),
 array([[ 3,  4,  3],
        [ 1,  3,  2],
        [ 9,  8, -1]]),
 array([1]),
 array([1]))